### ISSUE TITLE
compute instance not applying changes

### ISSUE THREAD

**Issue by ziporah** [terraform-google-modules/terraform-google-container-vm#24] opened 2019-05-22 08:06 UTC
When using the instance_with_attached_disk example I'm unable to make the changes apply on the instance when changing any paramters in the terraform configuration.
Example:
create config with
${var.image} = "gcr.io/google-samples/hello-app:1.0"
apply the terraform config. This results in a compute instance with hello-app docker container running.
Then alter the terraform.tfvars file to reflect the change below and apply.
${var.image} = "jenkins/jenkins:lts" 
The compute instance does not reflect the changes, while terraform plan has correctly updated the metadata information. 
Rebooting the compute instance recreates the container with correct specs, but I expect terraform / GCE to detect this change and automatically apply the reboot or am I missing some configuration that makes this possible?
I'v tried using terraform v0.11, since v0.12-rc1 crashes when trying to use the module.

**Comment by morgante** [comment] 2019-08-16 18:02
This looks like a duplicate of #29.

**Closed by morgante** 2019-08-16 18:02 UTC
Labels: bug
